--- 
title: "Everything I Know About Stats"
author: "Sam Henderson-Palmer"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
description: |
  These are all my stats notes.
link-citations: yes
github-repo: samhendersonpalmer/StatsNotes
---

# About

These are notes from various course, books and talks that I'm keeping a note of for future use

## Quick definitions

**95% confidence interval:** We can say with 95% certainty/confidence that the true population parameter of interest lies within the interval upon repeated sampling of the population. Or Ben Goldacres definition (from page 60 of "It's a bit more complicated than that"):

> "it means that if you repeatedly took samples of a hundred, then on 95 per cent of those attempts, the true [parameter] would lie somewhere between the upper and lower limits of the 95 per cent confidence intervals of yout samples."

## General programming tips

### This book
To preview a specific page to prevent building the whole thing just do `bookdown::preview_chapter("01-intro.Rmd", 'bookdown::gitbook')` then open the corresponding html file within the `_book/` folder.

### Project structure - Example of this [here](https://github.com/stangandaho/nest-tree-selection/tree/main)

* README.md - Project overview, usage and dependencies
* setup.R - Install and loads required packages (called at the top of each script)
* utils.R - General utility functions (i.e. custom functions used within scripts repeatedly)
* datasets/ - Stores raw and cleaned data
* scripts/ - Holds processing, viz and analysis scripts
* plots/ - Saves generated images and plots
* tables/ - Store exported analysis tables
* fonts/ (if needed for custom viz)


## Quotes

> "We are barraged, every day, with a vast quantity of numerical data, presented with absolute certainty and fetishistic precision. In reality, many of these numbers amount to nothing more than statistical noise, the gentle static fuzz of random variation and sampling error, making figures drift up and down, following no pattern at all, like the changing roll of a dice. This, I confidently predict, will never change" Ben Goldacre, pg 61 "It's a bit more complicated than that"
